### ISSUE TITLE
How to enable Free Shipping?

### ISSUE THREAD

**Issue by Jeeva-Rathinam** [kirchbergerknorr/Webshopapps_Matrixrate#1]
How to give free shipping using Webshopapps  Matrix Rates in SHopping Cart Pricing rule?

**Comment by Lmbrtz** [comment]
Hi Jeeva-Rathinam,
please note we are not the developer of this extension. For any questions, please have a look at the official module documentation: https://webshopapps.com/eu/matrixrate-shipping-extension.html.

Please also note the notice in the readme: this module appears not to be working.
